import Head from 'next/head'

import Masthead from '../components/Masthead/masthead'
import Aboutus from '../components/AboutUs/aboutus'
import Skills from '../components/Skills/skills'
import Works from '../components/Works/works'
import TrustedBy from '../components/TrustedBy/trustedby'
import ContactUs from '../components/Contact/contactus'
import Footer from '../components/Footer/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sasha's app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead/>
      <Aboutus/>
      <Skills/>
      <Works/>
      <TrustedBy/>
      <ContactUs/>
      <Footer/>
    </div>
  )
}
